global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8001']

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8003']
