{
 "title": "Transaction Generator Data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transactions Generated",
   "type": "stat",
   "description": "Total number of transactions generated by each instance",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (transactions_generated_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Transaction Latency",
   "type": "timeseries",
   "description": "1 minute rolling average of transaction latency",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(transaction_latency_seconds_sum[1m])) by(instance) / sum(rate(transaction_latency_seconds_count[1m])) by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transaction Errors",
   "type": "timeseries",
   "description": "Amount of failed transactions over time",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(transaction_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}